Spring:
  Datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    username: root

  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL8Dialect
      driverClassName: com.mysql.cj.jdbc.Drive
    database: mysql
